<a href="https://colab.research.google.com/github/MathewBiddle/map-of-activities/blob/main/MBON_harvest_registration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install selenium beautifulsoup4 requests

Requirement already satisfied: selenium in /usr/local/lib/python3.11/dist-packages (4.29.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (4.13.3)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (2.32.3)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.11/dist-packages (from urllib3[socks]<3,>=1.26->selenium) (2.3.0)
Requirement already satisfied: trio~=0.17 in /usr/local/lib/python3.11/dist-packages (from selenium) (0.29.0)
Requirement already satisfied: trio-websocket~=0.9 in /usr/local/lib/python3.11/dist-packages (from selenium) (0.12.2)
Requirement already satisfied: certifi>=2021.10.8 in /usr/local/lib/python3.11/dist-packages (from selenium) (2025.1.31)
Requirement already satisfied: typing_extensions~=4.9 in /usr/local/lib/python3.11/dist-packages (from selenium) (4.12.2)
Requirement already satisfied: websocket-client~=1.8 in /usr/local/lib/python3.11/dist-packages (from selenium) (1.8.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4) (2.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests) (3.10)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.11/dist-packages (from trio~=0.17->selenium) (25.2.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.11/dist-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: outcome in /usr/local/lib/python3.11/dist-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.11/dist-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [2]:
## For google spreadsheet reading you need to authenticate w/ google

import pandas as pd

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

In [3]:
def get_sheet_data(url: str, sheet: str) -> pd.DataFrame:
  '''
  Gets data from specific worksheet in Google Spreadsheet and
  returns as a DataFrame.

  parameters:
  sheet (str): name of worksheet, eg 'Form Responses 1'

  returns:
  DataFrame: worksheet data as a DataFrame

  '''

  worksheet = gc.open_by_url(url)
  room_n = worksheet.worksheet(sheet)

  df = pd.DataFrame(room_n.get_all_records())

  return df

In [4]:
url = 'https://docs.google.com/spreadsheets/d/1jBS8ASS27yV8APZ8Fh-tgX6dHdopwianrUZv0kbKcxw/edit?gid=1698140136#gid=1698140136'
sheet = 'Form Responses 1'

df = get_sheet_data(url, sheet)

df = df.replace('(?i)yes$',True, regex=True).replace('(?i)no$',False,regex=True)

df.sample(4)

,Timestamp,Dataset title,Dataset summary,Crossfunded? (Yes/No),Who is the data management POC for the dataset?,Data management POC email:,Who is the technical POC for the dataset?,Technical POC email:,Which MBON project is this dataset associated with?,"If you have worked with a Regional Association, please indicate which one(s).",...,Upload the dataset.,Are there scripts or code used to process the data?,"If yes to above, and they are publicly available, please include appropriate link(s) here.","If yes to above, and the code is available, please include appropriate link(s) here.",Would you like this dataset visualized in the MBON Data Portal (https://mbon.ioos.us/)?,Email Address,"If the dataset is already visualized in the MBON data portal, please include the link(s) to the data layer(s) here.",,What is the expected timeline for this dataset?,additonal comments
27,10/19/2021 14:22,Santa Barbara Channel Coastal and Island fish ...,citizen scientist monitoring data for rocky re...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,,,,,,,
9,9/10/2024 15:14:29,FKNMS Cruises CTD data,"Bathymetry, nutrients, and more collected by t...",,Ian Smith,Ian.Smith@noaa.gov,Ian Smith,Ian.Smith@noaa.gov,SE US,GCOOS,...,,True,https://github.com/USF-IMARS/seus-mbon-cruise-...,,True,murray.tylar@gmail.com,,,,
35,10/19/2021 14:22,Abundance and species composition of benthic h...,counts of heterobranch molluscs (sea slugs and...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,,,,,,,
54,8/5/2021 16:00:15,Benthic Epifauna Biomass and Abundance Data in...,This dataset contains benthic epifauna biomass...,,False,adrienne@axiomdatascience.com,Katrin Iken,kbiken@alaska.edu,Arctic,AOOS,...,,True,,,True,,https://mbon.ioos.us/#metadata/9649bae5-3020-4...,,,

## Function to extract json-ld from webpage

In [5]:
from selenium import webdriver
from bs4 import BeautifulSoup
import json
import requests

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')  # Run Chrome in headless mode
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')

def get_ld_json(url: str) -> dict:
    parser = "lxml"
    req = requests.get(url)
    soup = BeautifulSoup(req.text, parser)
    return json.loads("".join(soup.find("script", {"type":"application/ld+json"}).contents))

## Check through datasets that have a link to a repository and extract json-ld

In [6]:
df['spatialCoverage'] = pd.Series()

for index, row in df.loc[df['If yes to above, please include appropriate link(s) here.']!='',['If yes to above, please include appropriate link(s) here.','Dataset title']].iterrows():

  url = row['If yes to above, please include appropriate link(s) here.']
  title = row['Dataset title']


  if url.startswith('10.154'):
    url = f'https://dx.doi.org/{url}'
    #print(f'{url}\n')

  elif '\ndata can also be accessed by using the repository\'s API.' in url:
    url = url.replace('data can also be accessed by using the repository\'s API.','')
    #print(f'{url}\n')

  elif url.endswith('.pdf'):
    continue

  elif 'usf.box.com' in url:
    continue

  elif 'neracoos.org/erddap' in url:
    # NERACOOS is running an old ERDDAP which represents
    # schema.org bounding box incorrectly. See
    # https://erddap.github.io/changes#version-200
    continue

  try:
    spatial = get_ld_json(url)['spatialCoverage']['geo']
    print(f'{url} has spatial {spatial}')
    df.loc[df['Dataset title'] == title, 'spatialCoverage'] = [spatial]

  except:

    try:

      browser = webdriver.Chrome(options=chrome_options)
      browser.get(url)
      html_source = browser.page_source
      soup = BeautifulSoup(html_source, 'lxml')
      spatial = json.loads("".join(soup.find("script", {"type":"application/ld+json"}).contents))
      spatial = spatial['spatialCoverage']['geo']
      df.loc[df['Dataset title'] == title, 'spatialCoverage'] = [spatial]

    except:
      print(f'{url} cant find json-ld')

https://dx.doi.org/10.15468/bfd6ci cant find json-ld
https://dx.doi.org/10.15468/h585qq has spatial {'@type': 'GeoShape', 'box': '24.647 26.785 -82.705 -79.277'}
https://grunt.sefsc.noaa.gov/rvc_analysis20/samples/index cant find json-ld
https://ecotaxa.obs-vlfr.fr/prj/9989 cant find json-ld
https://data.piscoweb.org/metacatui/view/doi%3A10.6085%2FAA%2Fmarine_cbs.5.6 cant find json-ld
https://pubmed.ncbi.nlm.nih.gov/29937700/ cant find json-ld
https://dx.doi.org/10.15468/buqg4u  has spatial {'@type': 'GeoShape', 'box': '24.476 25.006 -81.715 -80.379'}
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=5 has spatial [{'@type': 'GeoShape', 'box': '32.8 -120.6344833 34.87315 -118.4'}]
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=3 has spatial [{'@type': 'GeoShape', 'box': '32.8 -120.65022 34.87315 -118.4'}]
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=7 has spatial [{'@type': 'GeoShape', 'box': '32.8 -120.65022 34.87315 -118.4'}]
https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=74 has spatial [{'@type': 'GeoShape', 'box': '27.01 -124.77 48.40 -114.04'}]
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=141 has spatial [{'@type': 'GeoShape', 'box': '34.4030 -120.0669 34.4611 -119.8660'}]
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=484 has spatial [{'@type': 'GeoCoordinates', 'latitude': '34.01683333', 'longitude': '-119.361475'}, {'@type': 'GeoCoordinates', 'latitude': '34.40002778', 'longitude': '-119.7446056'}, {'@type': 'GeoCoordinates', 'latitude': '34.46931111', 'longitude': '-120.1248722'}, {'@type': 'GeoCoordinates', 'latitude': '34.392222', 'longitude': '-119.5428164'}, {'@type': 'GeoCoordinates', 'latitude': '34.015556', 'longitude': '-119.371102'}, {'@type': 'GeoCoordinates', 'latitude': '34.05784333', 'longitude': '-120.354022'}, {'@type': 'GeoCoordinates', 'latitude': '34.05715133', 'longitude': '-119.7646803'}, {'@type': 'GeoCoordinates', 'latitude': '34.41775244', 'longitude': '-119.9012928'}, {'@type': 'GeoCoordinates', 'latitude': '34.055492', 'longitude': '-119.7552165'}, {'@type': 'GeoCoordinates', 'latitude': '33.9510315', 'longitude': '-119.82651'}, {'@type': 'GeoCoordinates', 'latitude': '33.72641433', 'longitude': '-119.8285767'}, {'@type': 'GeoCoordinates', 'latitude': '34.4034', 'longitude': '-119.85728'}, {'@type': 'GeoCoordinates', 'latitude': '33.90137333', 'longitude': '-120.1027767'}, {'@type': 'GeoCoordinates', 'latitude': '34.39438878', 'longitude': '-119.7291667'}, {'@type': 'GeoCoordinates', 'latitude': '34.42235', 'longitude': '-119.9529333'}, {'@type': 'GeoCoordinates', 'latitude': '34.03394267', 'longitude': '-119.7020243'}, {'@type': 'GeoCoordinates', 'latitude': '34.02285383', 'longitude': '-119.6879698'}, {'@type': 'GeoCoordinates', 'latitude': '34.03277565', 'longitude': '-120.1088442'}, {'@type': 'GeoCoordinates', 'latitude': '34.0456535', 'longitude': '-119.544324'}, {'@type': 'GeoCoordinates', 'latitude': '34.30692667', 'longitude': '-119.3630553'}, {'@type': 'GeoCoordinates', 'latitude': '34.00689978', 'longitude': '-119.431383'}, {'@type': 'GeoCoordinates', 'latitude': '33.99277767', 'longitude': '-119.5635321'}]
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=484 cant find json-ld
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=110 has spatial [{'@type': 'GeoShape', 'box': '33.91 -119.52 34.01 -119.45'}]
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=485 cant find json-ld
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=486 has spatial [{'@type': 'GeoShape', 'box': '31.9 -121.15 34.5 -117.27'}]
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=134 has spatial [{'@type': 'GeoShape', 'box': '33.3 -79.21 33.38 -79.17'}]
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=91 has spatial [{'@type': 'GeoShape', 'box': '40.23 -96.34 43.25 -90.12'}]
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=51 has spatial [{'@type': 'GeoShape', 'box': '33.185566666666666 -81.75708055555556 33.372280555555555 -81.50800833333334'}]
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=646 has spatial [{'@type': 'GeoCoordinates', 'latitude': '34.4339', 'longitude': '-119.95'}, {'@type': 'GeoCoordinates', 'latitude': '34.3869', 'longitude': '-119.5165'}]
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=646 cant find json-ld
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=111 has spatial [{'@type': 'GeoShape', 'box': '33.56 -120.73 34.61 -118.11'}]
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=112 has spatial [{'@type': 'GeoShape', 'box': '34.48 -120.487 34.013 -119.379'}]
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=113 has spatial [{'@type': 'GeoShape', 'box': '33.56 -120.73 34.61 -118.11'}]
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=470 has spatial [{'@type': 'GeoCoordinates', 'latitude': '34.37', 'longitude': '-120.16'}]
https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=61 has spatial [{'@type': 'GeoCoordinates', 'latitude': '34.400275', 'longitude': '-119.7445915'}, {'@type': 'GeoCoordinates', 'latitude': '34.471817', 'longitude': '-120.1426165'}, {'@type': 'GeoCoordinates', 'latitude': '34.46774988', 'longitude': '-120.11905'}, {'@type': 'GeoCoordinates', 'latitude': '34.45850533', 'longitude': '-120.33349'}, {'@type': 'GeoCoordinates', 'latitude': '34.3916319', 'longitude': '-119.5416933'}, {'@type': 'GeoCoordinates', 'latitude': '34.4137165', 'longitude': '-119.8221'}, {'@type': 'GeoCoordinates', 'latitude': '34.402783', 'longitude': '-119.85755'}, {'@type': 'GeoCoordinates', 'latitude': '34.3940708', 'longitude': '-119.72957'}, {'@type': 'GeoCoordinates', 'latitude': '34.4221216', 'longitude': '-119.95154'}, {'@type': 'GeoCoordinates', 'latitude': '34.05865', 'longitude': '-119.75763'}, {'@type': 'GeoCoordinates', 'latitude': '34.0444335', 'longitude': '-119.71513'}, {'@type': 'GeoCoordinates', 'latitude': '34.05695', 'longitude': '-119.7551'}, {'@type': 'GeoCoordinates', 'latitude': '34.05765', 'longitude': '-119.7558833'}, {'@type': 'GeoCoordinates', 'latitude': '34.05776667', 'longitude': '-119.7563'}, {'@type': 'GeoCoordinates', 'latitude': '34.05365', 'longitude': '-119.7496333'}, {'@type': 'GeoCoordinates', 'latitude': '34.05291667', 'longitude': '-119.7470333'}, {'@type': 'GeoCoordinates', 'latitude': '34.05076667', 'longitude': '-119.7414167'}, {'@type': 'GeoCoordinates', 'latitude': '34.05116667', 'longitude': '-119.7418167'}, {'@type': 'GeoCoordinates', 'latitude': '34.05035', 'longitude': '-119.7406333'}, {'@type': 'GeoCoordinates', 'latitude': '34.0444', 'longitude': '-119.7151333'}, {'@type': 'GeoCoordinates', 'latitude': '34.04345', 'longitude': '-119.7140833'}]
https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=61 cant find json-ld
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=257 has spatial [{'@type': 'GeoCoordinates', 'latitude': '34.40766', 'longitude': '-119.877969'}]
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=109 has spatial [{'@type': 'GeoShape', 'box': '29.8 -124.333336 35.093334 -117.28333'}, {'@type': 'GeoCoordinates', 'latitude': '32.95637', 'longitude': '-117.30538'}, {'@type': 'GeoCoordinates', 'latitude': '32.91304', 'longitude': '-117.39438'}, {'@type': 'GeoCoordinates', 'latitude': '32.84637', 'longitude': '-117.53122'}, {'@type': 'GeoCoordinates', 'latitude': '32.67971', 'longitude': '-117.87286'}, {'@type': 'GeoCoordinates', 'latitude': '32.51304', 'longitude': '-118.21386'}, {'@type': 'GeoCoordinates', 'latitude': '32.34637', 'longitude': '-118.55423'}, {'@type': 'GeoCoordinates', 'latitude': '32.17971', 'longitude': '-118.89396'}, {'@type': 'GeoCoordinates', 'latitude': '32.01304', 'longitude': '-119.23306'}, {'@type': 'GeoCoordinates', 'latitude': '31.84637', 'longitude': '-119.57154'}, {'@type': 'GeoCoordinates', 'latitude': '31.51304', 'longitude': '-120.24666'}, {'@type': 'GeoCoordinates', 'latitude': '31.17971', 'longitude': '-120.91935'}, {'@type': 'GeoCoordinates', 'latitude': '30.84637', 'longitude': '-121.58965'}, {'@type': 'GeoCoordinates', 'latitude': '30.51304', 'longitude': '-122.2576'}, {'@type': 'GeoCoordinates', 'latitude': '30.17971', 'longitude': '-122.92324'}, {'@type': 'GeoCoordinates', 'latitude': '29.84637', 'longitude': '-123.58661'}, {'@type': 'GeoCoordinates', 'latitude': '30.41795', 'longitude': '-123.99893'}, {'@type': 'GeoCoordinates', 'latitude': '30.75128', 'longitude': '-123.33164'}, {'@type': 'GeoCoordinates', 'latitude': '31.08462', 'longitude': '-122.66202'}, {'@type': 'GeoCoordinates', 'latitude': '31.41795', 'longitude': '-121.99001'}, {'@type': 'GeoCoordinates', 'latitude': '31.75128', 'longitude': '-121.31559'}, {'@type': 'GeoCoordinates', 'latitude': '32.08462', 'longitude': '-120.63872'}, {'@type': 'GeoCoordinates', 'latitude': '32.41795', 'longitude': '-119.95935'}, {'@type': 'GeoCoordinates', 'latitude': '32.65128', 'longitude': '-119.48228'}, {'@type': 'GeoCoordinates', 'latitude': '32.91795', 'longitude': '-118.93551'}, {'@type': 'GeoCoordinates', 'latitude': '33.18462', 'longitude': '-118.38708'}, {'@type': 'GeoCoordinates', 'latitude': '33.25128', 'longitude': '-118.24971'}, {'@type': 'GeoCoordinates', 'latitude': '33.41795', 'longitude': '-117.90582'}, {'@type': 'GeoCoordinates', 'latitude': '33.48462', 'longitude': '-117.76808'}, {'@type': 'GeoCoordinates', 'latitude': '33.88953', 'longitude': '-118.49033'}, {'@type': 'GeoCoordinates', 'latitude': '33.82286', 'longitude': '-118.62873'}, {'@type': 'GeoCoordinates', 'latitude': '33.65619', 'longitude': '-118.97425'}, {'@type': 'GeoCoordinates', 'latitude': '33.48953', 'longitude': '-119.3191'}, {'@type': 'GeoCoordinates', 'latitude': '33.32286', 'longitude': '-119.66327'}, {'@type': 'GeoCoordinates', 'latitude': '33.15619', 'longitude': '-120.00678'}, {'@type': 'GeoCoordinates', 'latitude': '32.98953', 'longitude': '-120.34964'}, {'@type': 'GeoCoordinates', 'latitude': '32.65619', 'longitude': '-121.03339'}, {'@type': 'GeoCoordinates', 'latitude': '32.32286', 'longitude': '-121.71457'}, {'@type': 'GeoCoordinates', 'latitude': '31.98953', 'longitude': '-122.39323'}, {'@type': 'GeoCoordinates', 'latitude': '31.65619', 'longitude': '-123.0694'}, {'@type': 'GeoCoordinates', 'latitude': '31.32286', 'longitude': '-123.74313'}, {'@type': 'GeoCoordinates', 'latitude': '31.91176', 'longitude': '-124.1704'}, {'@type': 'GeoCoordinates', 'latitude': '32.24509', 'longitude': '-123.49232'}, {'@type': 'GeoCoordinates', 'latitude': '32.57842', 'longitude': '-122.81173'}, {'@type': 'GeoCoordinates', 'latitude': '32.91176', 'longitude': '-122.12858'}, {'@type': 'GeoCoordinates', 'latitude': '33.24509', 'longitude': '-121.44283'}, {'@type': 'GeoCoordinates', 'latitude': '33.57842', 'longitude': '-120.75443'}, {'@type': 'GeoCoordinates', 'latitude': '33.74509', 'longitude': '-120.40923'}, {'@type': 'GeoCoordinates', 'latitude': '33.87842', 'longitude': '-120.13258'}, {'@type': 'GeoCoordinates', 'latitude': '34.17842', 'longitude': '-119.50851'}, {'@type': 'GeoCoordinates', 'latitude': '34.22509', 'longitude': '-119.41124'}, {'@type': 'GeoCoordinates', 'latitude': '34.2749', 'longitude': '-120.02524'}, {'@type': 'GeoCoordinates', 'latitude': '34.45', 'longitude': '-120.5239'}, {'@type': 'GeoCoordinates', 'latitude': '34.31667', 'longitude': '-120.80245'}, {'@type': 'GeoCoordinates', 'latitude': '34.15', 'longitude': '-121.15'}, {'@type': 'GeoCoordinates', 'latitude': '33.81667', 'longitude': '-121.84304'}, {'@type': 'GeoCoordinates', 'latitude': '33.48333', 'longitude': '-122.53335'}, {'@type': 'GeoCoordinates', 'latitude': '33.15', 'longitude': '-123.22099'}, {'@type': 'GeoCoordinates', 'latitude': '32.81667', 'longitude': '-123.90599'}, {'@type': 'GeoCoordinates', 'latitude': '33.38824', 'longitude': '-124.32289'}, {'@type': 'GeoCoordinates', 'latitude': '33.72158', 'longitude': '-123.63335'}, {'@type': 'GeoCoordinates', 'latitude': '34.05491', 'longitude': '-122.94109'}, {'@type': 'GeoCoordinates', 'latitude': '34.38824', 'longitude': '-122.24608'}, {'@type': 'GeoCoordinates', 'latitude': '34.72158', 'longitude': '-121.54828'}, {'@type': 'GeoCoordinates', 'latitude': '34.88824', 'longitude': '-121.19831'}, {'@type': 'GeoCoordinates', 'latitude': '35.02158', 'longitude': '-120.91782'}, {'@type': 'GeoCoordinates', 'latitude': '35.08824', 'longitude': '-120.7774'}]
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=109 cant find json-ld
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier1145 cant find json-ld
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=702 has spatial [{'@type': 'GeoCoordinates', 'latitude': ' 34.416667', 'longitude': '-119.95'}, {'@type': 'GeoCoordinates', 'latitude': ' 34.466667', 'longitude': '-120.116667'}, {'@type': 'GeoCoordinates', 'latitude': '34.383333', 'longitude': '-119.716667'}, {'@type': 'GeoCoordinates', 'latitude': ' 34.40', 'longitude': '-119.866667'}]
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=702 cant find json-ld
https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-cce&identifier=255 cant find json-ld
https://data.piscoweb.org/metacatui/view/doi%3A10.6085%2FAA%2Fmarine_ltm.12.5 cant find json-ld
https://www.glerl.noaa.gov/glansis/mapExplorer.php cant find json-ld
https://www.glerl.noaa.gov/data/waterlife/ cant find json-ld
https://cwcgom.aoml.noaa.gov/thredds/dodsC/SEASCAPE_8DAY/SEASCAPES.nc cant find json-ld
https://obis.org/dataset/afef5da2-614b-4208-aee6-c2413ed5ab76 has spatial {'@type': 'GeoShape', 'polygon': '-81.717 24.478,-81.717 25.35167,-80.38 25.35167,-80.38 24.478,-81.717 24.478'}
https://opc.dataone.org/view/doi%3A10.25494%2FP6901R cant find json-ld
https://opc.dataone.org/view/doi%3A10.25494%2FP6JS3M
https://opc.dataone.org/view/doi%3A10.25494%2FP69885
https://opc.dataone.org/view/doi%3A10.25494%2FP65K5W
https://opc.dataone.org/view/doi%3A10.25494%2FP6F30N cant find json-ld
https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.nodc:0177837 cant find json-ld
https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=5 has spatial [{'@type': 'GeoShape', 'box': '32.8 -120.6344833 34.87315 -118.4'}]

## Extract coordinate information

Add coordinate information from schema.org back into the DataFrame.

In [7]:
df = pd.concat([df, pd.json_normalize(df['spatialCoverage'])], axis=1)

df.loc[~df['spatialCoverage'].isna()]

,Timestamp,Dataset title,Dataset summary,Crossfunded? (Yes/No),Who is the data management POC for the dataset?,Data management POC email:,Who is the technical POC for the dataset?,Technical POC email:,Which MBON project is this dataset associated with?,"If you have worked with a Regional Association, please indicate which one(s).",...,"If the dataset is already visualized in the MBON data portal, please include the link(s) to the data layer(s) here.",,What is the expected timeline for this dataset?,additonal comments,spatialCoverage,@type,box,latitude,longitude,polygon
2,9/10/2024 15:27:50,South Florida Fisheries Habitat Assessment (FW...,taxa occurrence. Six seagrass species; ~36k re...,,Luke McEachron,Lucas.McEachron@myfwc.com,Luke McEachron,Lucas.McEachron@myfwc.com,SE US,,...,,,,,"{'@type': 'GeoShape', 'box': '24.647 26.785 -8...",GeoShape,24.647 26.785 -82.705 -79.277,NaN,NaN,NaN
21,6/20/2023 13:47:54,Time series of zooplankton abundance in South ...,Sampling are carried out bi-monthly on the R/V...,,"Digna Rueda-Roa (College of Marine Science, Un...",druedaro@usf.edu,Tylar Murray / Sebastian DiGeronimo (College ...,tylarmurray@usf.edu / sebastian15@usf.edu,SE US,GCOOS,...,,,"Please, put this in hold. \nWe uploaded a part...",,"{'@type': 'GeoShape', 'box': '24.476 25.006 -8...",GeoShape,24.476 25.006 -81.715 -80.379,NaN,NaN,NaN
23,10/19/2021 14:22,Santa Barbara Channel Marine BON: Nearshore ke...,This dataset contains counts of epibenthic alg...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,,"{'@type': 'GeoShape', 'box': '32.8 -120.634483...",GeoShape,32.8 -120.6344833 34.87315 -118.4,NaN,NaN,NaN
24,10/19/2021 14:22,Southern California Bight Marine BON: Integrat...,This dataset contains cover of kelp forest ses...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,,"{'@type': 'GeoShape', 'box': '32.8 -120.65022 ...",GeoShape,32.8 -120.65022 34.87315 -118.4,NaN,NaN,NaN
25,10/19/2021 14:22,Southern California Bight Marine BON: cummulat...,Dataset contains all species from datasets of ...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,,"{'@type': 'GeoShape', 'box': '32.8 -120.65022 ...",GeoShape,32.8 -120.65022 34.87315 -118.4,NaN,NaN,NaN
26,10/19/2021 14:22,SBC LTER: Time series of quarterly NetCDF file...,This data is a time series of canopy area of g...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,,"{'@type': 'GeoShape', 'box': '27.01 -124.77 48...",GeoShape,27.01 -124.77 48.40 -114.04,NaN,NaN,NaN
27,10/19/2021 14:22,Santa Barbara Channel Coastal and Island fish ...,citizen scientist monitoring data for rocky re...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,,"{'@type': 'GeoShape', 'box': '34.4030 -120.066...",GeoShape,34.4030 -120.0669 34.4611 -119.8660,NaN,NaN,NaN
29,10/19/2021 14:22,Santa Barbara Channel fish surveys at deep ree...,fish surveys from deep natural reefs in the no...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,,"{'@type': 'GeoShape', 'box': '33.91 -119.52 34...",GeoShape,33.91 -119.52 34.01 -119.45,NaN,NaN,NaN
31,10/19/2021 14:22,NWFSC fish and invertebrate diversity derived ...,This dataset presents the community structure ...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,,"{'@type': 'GeoShape', 'box': '31.9 -121.15 34....",GeoShape,31.9 -121.15 34.5 -117.27,NaN,NaN,NaN
32,10/19/2021 14:22,Plumes and Blooms: Curated oceanographic and p...,"The Plumes and Blooms project (PnB), has condu...",,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,,"{'@type': 'GeoShape', 'box': '33.3 -79.21 33.3...",GeoShape,33.3 -79.21 33.38 -79.17,NaN,NaN,NaN
33,10/19/2021 14:22,SBC LTER: Beach: Time-series of beach wrack co...,"composition, count, and wet biomass of macroin...",,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,,"{'@type': 'GeoShape', 'box': '40.23 -96.34 43....",GeoShape,40.23 -96.34 43.25 -90.12,NaN,NaN,NaN
34,10/19/2021 14:22,SBC LTER: Beach: Time series of abundance of b...,"distribution, abundance and seasonal occurrenc...",,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,,"{'@type': 'GeoShape', 'box': '33.1855666666666...",GeoShape,33.185566666666666 -81.75708055555556 33.37228...,NaN,NaN,NaN
36,10/19/2021 14:22,Santa Barbara Channel fish and invertebrate su...,Counts of fish and invertebrates at nine oil a...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,,"{'@type': 'GeoShape', 'box': '33.56 -120.73 34...",GeoShape,33.56 -120.73 34.61 -118.11,NaN,NaN,NaN
37,10/19/2021 14:22,Santa Barbara Channel fish surveys at shallow ...,"Fish surveys at nine nearshore, shallow-water ...",,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,,"{'@type': 'GeoShape', 'box': '34.48 -120.487 3...",GeoShape,34.48 -120.487 34.013 -119.379,NaN,NaN,NaN
38,10/19/2021 14:22,Santa Barbara Channel fish surveys at shallow ...,fish counts surveyed in the shallow sections (...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,,"{'@type': 'GeoShape', 'box': '33.56 -120.73 34...",GeoShape,33.56 -120.73 34.61 -118.11,NaN,NaN,NaN
39,10/19/2021 14:22,Data to support manuscript: A Comparison of Tw...,fish dataset was collected at platform Harmony...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,,"{'@type': 'GeoCoordinates', 'latitude': '34.37...",GeoCoordinates,NaN,34.37,-120.16,NaN
41,10/19/2021 14:22,Santa Barbara Channel Marine BON: Gray Whales ...,dataset documents the passage of gray whales (...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,,"{'@type': 'GeoCoordinates', 'latitude': '34.40...",GeoCoordinates,NaN,34.40766,-119.877969,NaN
51,8/9/2021 16:46:29,Time series of zooplankton abundance of the So...,Sampling is carried out bi-monthly on the R/V ...,,Enrique Montes (College of Marine Science of t...,emontesh@usf.edu,Tylar Murray (College of Marine Science of the...,tylarmurray@usf.edu,SE US,GCOOS,...,,,,5/3/2022: put this on hold because all we can ...,"{'@type': 'GeoShape', 'polygon': '-81.717 24.4...",GeoShape,NaN,NaN,NaN,"-81.717 24.478,-81.717 25.35167,-80.38 25.3516..."
55,8/4/2021 20:06:46,"Nearshore kelp forest integrated fish, 1981-on...",This dataset contains counts of fish (includin...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,https://mbon.ioos.us/#module-metadata/746cc92f...,,,,"{'@type': 'GeoShape', 'box': '32.8 -120.634483...",GeoShape,32.8 -120.6344833 34.87315 -118.4,NaN,NaN,NaN

## Box

In [8]:
import geopandas as gpd

test = df.loc[~df['box'].isna()]

# read from 'box'
def box_to_wkt(box_str):
       """Converts a box string to WKT format."""
       try:
           # Assuming box_str is in the format 'north, west, south, east'
           south, west, north, east = map(float, box_str.split(' '))
           # Create WKT polygon string
           wkt_polygon = f'POLYGON(({west} {north}, {east} {north}, {east} {south}, {west} {south}, {west} {north}))'
           return wkt_polygon
       except (ValueError, AttributeError):
           # Handle cases where box_str is not in the expected format or is None
           return None

test['wkt'] = test['box'].apply(box_to_wkt)

#test['geometry'] = gpd.GeoSeries.from_wkt(test['wkt'], crs='EPSG:4326')

#test

df.loc[~df['box'].isna(),'wkt'] = test['wkt']

df.loc[~df['box'].isna()]
# read 'box' into geometry somehow
#gpd.GeoSeries.from_wkt(df['box'])

<ipython-input-8-65551a2ccba0>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['wkt'] = test['box'].apply(box_to_wkt)

,Timestamp,Dataset title,Dataset summary,Crossfunded? (Yes/No),Who is the data management POC for the dataset?,Data management POC email:,Who is the technical POC for the dataset?,Technical POC email:,Which MBON project is this dataset associated with?,"If you have worked with a Regional Association, please indicate which one(s).",...,,What is the expected timeline for this dataset?,additonal comments,spatialCoverage,@type,box,latitude,longitude,polygon,wkt
2,9/10/2024 15:27:50,South Florida Fisheries Habitat Assessment (FW...,taxa occurrence. Six seagrass species; ~36k re...,,Luke McEachron,Lucas.McEachron@myfwc.com,Luke McEachron,Lucas.McEachron@myfwc.com,SE US,,...,,,,"{'@type': 'GeoShape', 'box': '24.647 26.785 -8...",GeoShape,24.647 26.785 -82.705 -79.277,NaN,NaN,NaN,"POLYGON((26.785 -82.705, -79.277 -82.705, -79...."
21,6/20/2023 13:47:54,Time series of zooplankton abundance in South ...,Sampling are carried out bi-monthly on the R/V...,,"Digna Rueda-Roa (College of Marine Science, Un...",druedaro@usf.edu,Tylar Murray / Sebastian DiGeronimo (College ...,tylarmurray@usf.edu / sebastian15@usf.edu,SE US,GCOOS,...,,"Please, put this in hold. \nWe uploaded a part...",,"{'@type': 'GeoShape', 'box': '24.476 25.006 -8...",GeoShape,24.476 25.006 -81.715 -80.379,NaN,NaN,NaN,"POLYGON((25.006 -81.715, -80.379 -81.715, -80...."
23,10/19/2021 14:22,Santa Barbara Channel Marine BON: Nearshore ke...,This dataset contains counts of epibenthic alg...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,"{'@type': 'GeoShape', 'box': '32.8 -120.634483...",GeoShape,32.8 -120.6344833 34.87315 -118.4,NaN,NaN,NaN,"POLYGON((-120.6344833 34.87315, -118.4 34.8731..."
24,10/19/2021 14:22,Southern California Bight Marine BON: Integrat...,This dataset contains cover of kelp forest ses...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,"{'@type': 'GeoShape', 'box': '32.8 -120.65022 ...",GeoShape,32.8 -120.65022 34.87315 -118.4,NaN,NaN,NaN,"POLYGON((-120.65022 34.87315, -118.4 34.87315,..."
25,10/19/2021 14:22,Southern California Bight Marine BON: cummulat...,Dataset contains all species from datasets of ...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,"{'@type': 'GeoShape', 'box': '32.8 -120.65022 ...",GeoShape,32.8 -120.65022 34.87315 -118.4,NaN,NaN,NaN,"POLYGON((-120.65022 34.87315, -118.4 34.87315,..."
26,10/19/2021 14:22,SBC LTER: Time series of quarterly NetCDF file...,This data is a time series of canopy area of g...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,"{'@type': 'GeoShape', 'box': '27.01 -124.77 48...",GeoShape,27.01 -124.77 48.40 -114.04,NaN,NaN,NaN,"POLYGON((-124.77 48.4, -114.04 48.4, -114.04 2..."
27,10/19/2021 14:22,Santa Barbara Channel Coastal and Island fish ...,citizen scientist monitoring data for rocky re...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,"{'@type': 'GeoShape', 'box': '34.4030 -120.066...",GeoShape,34.4030 -120.0669 34.4611 -119.8660,NaN,NaN,NaN,"POLYGON((-120.0669 34.4611, -119.866 34.4611, ..."
29,10/19/2021 14:22,Santa Barbara Channel fish surveys at deep ree...,fish surveys from deep natural reefs in the no...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,"{'@type': 'GeoShape', 'box': '33.91 -119.52 34...",GeoShape,33.91 -119.52 34.01 -119.45,NaN,NaN,NaN,"POLYGON((-119.52 34.01, -119.45 34.01, -119.45..."
31,10/19/2021 14:22,NWFSC fish and invertebrate diversity derived ...,This dataset presents the community structure ...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,"{'@type': 'GeoShape', 'box': '31.9 -121.15 34....",GeoShape,31.9 -121.15 34.5 -117.27,NaN,NaN,NaN,"POLYGON((-121.15 34.5, -117.27 34.5, -117.27 3..."
32,10/19/2021 14:22,Plumes and Blooms: Curated oceanographic and p...,"The Plumes and Blooms project (PnB), has condu...",,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,"{'@type': 'GeoShape', 'box': '33.3 -79.21 33.3...",GeoShape,33.3 -79.21 33.38 -79.17,NaN,NaN,NaN,"POLYGON((-79.21 33.38, -79.17 33.38, -79.17 33..."
33,10/19/2021 14:22,SBC LTER: Beach: Time-series of beach wrack co...,"composition, count, and wet biomass of macroin...",,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,"{'@type': 'GeoShape', 'box': '40.23 -96.34 43....",GeoShape,40.23 -96.34 43.25 -90.12,NaN,NaN,NaN,"POLYGON((-96.34 43.25, -90.12 43.25, -90.12 40..."
34,10/19/2021 14:22,SBC LTER: Beach: Time series of abundance of b...,"distribution, abundance and seasonal occurrenc...",,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,"{'@type': 'GeoShape', 'box': '33.1855666666666...",GeoShape,33.185566666666666 -81.75708055555556 33.37228...,NaN,NaN,NaN,POLYGON((-81.75708055555556 33.372280555555555...
36,10/19/2021 14:22,Santa Barbara Channel fish and invertebrate su...,Counts of fish and invertebrates at nine oil a...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,"{'@type': 'GeoShape', 'box': '33.56 -120.73 34...",GeoShape,33.56 -120.73 34.61 -118.11,NaN,NaN,NaN,"POLYGON((-120.73 34.61, -118.11 34.61, -118.11..."
37,10/19/2021 14:22,Santa Barbara Channel fish surveys at shallow ...,"Fish surveys at nine nearshore, shallow-water ...",,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,"{'@type': 'GeoShape', 'box': '34.48 -120.487 3...",GeoShape,34.48 -120.487 34.013 -119.379,NaN,NaN,NaN,"POLYGON((-120.487 34.013, -119.379 34.013, -11..."
38,10/19/2021 14:22,Santa Barbara Channel fish surveys at shallow ...,fish counts surveyed in the shallow sections (...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,"{'@type': 'GeoShape', 'box': '33.56 -120.73 34...",GeoShape,33.56 -120.73 34.61 -118.11,NaN,NaN,NaN,"POLYGON((-120.73 34.61, -118.11 34.61, -118.11..."
55,8/4/2021 20:06:46,"Nearshore kelp forest integrated fish, 1981-on...",This dataset contains counts of fish (includin...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,,"{'@type': 'GeoShape', 'box': '32.8 -120.634483...",GeoShape,32.8 -120.6344833 34.87315 -118.4,NaN,NaN,NaN,"POLYGON((-120.6344833 34.87315, -118.4 34.8731..."

In [9]:
df.loc[~df['box'].isna(),'box']

2                         24.647 26.785 -82.705 -79.277
21                        24.476 25.006 -81.715 -80.379
23                    32.8 -120.6344833 34.87315 -118.4
24                      32.8 -120.65022 34.87315 -118.4
25                      32.8 -120.65022 34.87315 -118.4
26                          27.01 -124.77 48.40 -114.04
27                  34.4030 -120.0669 34.4611 -119.8660
29                          33.91 -119.52 34.01 -119.45
31                            31.9 -121.15 34.5 -117.27
32                             33.3 -79.21 33.38 -79.17
33                            40.23 -96.34 43.25 -90.12
34    33.185566666666666 -81.75708055555556 33.37228...
36                          33.56 -120.73 34.61 -118.11
37                       34.48 -120.487 34.013 -119.379
38                          33.56 -120.73 34.61 -118.11
55                    32.8 -120.6344833 34.87315 -118.4
Name: box, dtype: object

## Polygon

In [10]:
temp=df.loc[~df['polygon'].isna()]

temp['wkt'] = 'POLYGON ((' + temp['polygon'].astype(str) + '))'

df.loc[~df['polygon'].isna(),'wkt'] = temp['wkt']

# gs = gpd.GeoSeries.from_wkt(temp['wkt'])

# gdf2 = gpd.GeoDataFrame(
#     temp,
#     geometry=gs,
#     crs='EPSG:4326'
#     )

# gdf.loc[~gdf['polygon'].isna(),'geometry'] = gdf2['geometry']


df.loc[~df['polygon'].isna()]
#gdf.merge(gdf2, how='inner', on='Dataset title')

<ipython-input-10-01eb75825acc>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['wkt'] = 'POLYGON ((' + temp['polygon'].astype(str) + '))'

,Timestamp,Dataset title,Dataset summary,Crossfunded? (Yes/No),Who is the data management POC for the dataset?,Data management POC email:,Who is the technical POC for the dataset?,Technical POC email:,Which MBON project is this dataset associated with?,"If you have worked with a Regional Association, please indicate which one(s).",...,,What is the expected timeline for this dataset?,additonal comments,spatialCoverage,@type,box,latitude,longitude,polygon,wkt
51,8/9/2021 16:46:29,Time series of zooplankton abundance of the So...,Sampling is carried out bi-monthly on the R/V ...,,Enrique Montes (College of Marine Science of t...,emontesh@usf.edu,Tylar Murray (College of Marine Science of the...,tylarmurray@usf.edu,SE US,GCOOS,...,,,5/3/2022: put this on hold because all we can ...,"{'@type': 'GeoShape', 'polygon': '-81.717 24.4...",GeoShape,NaN,NaN,NaN,"-81.717 24.478,-81.717 25.35167,-80.38 25.3516...","POLYGON ((-81.717 24.478,-81.717 25.35167,-80...."

## GeoCoordinates

In [11]:
import geopandas as gpd
temp = df.loc[df['@type']=='GeoCoordinates', ['latitude','longitude']]


gdf = gpd.GeoDataFrame(
    temp, geometry=gpd.points_from_xy(
        temp['longitude'],
        temp['latitude'])
    )

df.loc[df['@type']=='GeoCoordinates','geometry'] = gdf['geometry']

df.loc[df['@type']=='GeoCoordinates']

,Timestamp,Dataset title,Dataset summary,Crossfunded? (Yes/No),Who is the data management POC for the dataset?,Data management POC email:,Who is the technical POC for the dataset?,Technical POC email:,Which MBON project is this dataset associated with?,"If you have worked with a Regional Association, please indicate which one(s).",...,What is the expected timeline for this dataset?,additonal comments,spatialCoverage,@type,box,latitude,longitude,polygon,wkt,geometry
39,10/19/2021 14:22,Data to support manuscript: A Comparison of Tw...,fish dataset was collected at platform Harmony...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoCoordinates', 'latitude': '34.37...",GeoCoordinates,NaN,34.37,-120.16,NaN,NaN,POINT (-120.16 34.37)
41,10/19/2021 14:22,Santa Barbara Channel Marine BON: Gray Whales ...,dataset documents the passage of gray whales (...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoCoordinates', 'latitude': '34.40...",GeoCoordinates,NaN,34.40766,-119.877969,NaN,NaN,POINT (-119.87797 34.40766)

In [12]:
# wkt to geometry

temp = df.loc[~df['wkt'].isna()]

gs = gpd.GeoSeries.from_wkt(temp['wkt'])

gdf2 = gpd.GeoDataFrame(
    temp,
    geometry=gs,
    crs='EPSG:4326'
    )

df.loc[~df['wkt'].isna(),'geometry'] = gdf2['geometry']

df.loc[~df['wkt'].isna()]

,Timestamp,Dataset title,Dataset summary,Crossfunded? (Yes/No),Who is the data management POC for the dataset?,Data management POC email:,Who is the technical POC for the dataset?,Technical POC email:,Which MBON project is this dataset associated with?,"If you have worked with a Regional Association, please indicate which one(s).",...,What is the expected timeline for this dataset?,additonal comments,spatialCoverage,@type,box,latitude,longitude,polygon,wkt,geometry
2,9/10/2024 15:27:50,South Florida Fisheries Habitat Assessment (FW...,taxa occurrence. Six seagrass species; ~36k re...,,Luke McEachron,Lucas.McEachron@myfwc.com,Luke McEachron,Lucas.McEachron@myfwc.com,SE US,,...,,,"{'@type': 'GeoShape', 'box': '24.647 26.785 -8...",GeoShape,24.647 26.785 -82.705 -79.277,NaN,NaN,NaN,"POLYGON((26.785 -82.705, -79.277 -82.705, -79....","POLYGON ((26.785 -82.705, -79.277 -82.705, -79..."
21,6/20/2023 13:47:54,Time series of zooplankton abundance in South ...,Sampling are carried out bi-monthly on the R/V...,,"Digna Rueda-Roa (College of Marine Science, Un...",druedaro@usf.edu,Tylar Murray / Sebastian DiGeronimo (College ...,tylarmurray@usf.edu / sebastian15@usf.edu,SE US,GCOOS,...,"Please, put this in hold. \nWe uploaded a part...",,"{'@type': 'GeoShape', 'box': '24.476 25.006 -8...",GeoShape,24.476 25.006 -81.715 -80.379,NaN,NaN,NaN,"POLYGON((25.006 -81.715, -80.379 -81.715, -80....","POLYGON ((25.006 -81.715, -80.379 -81.715, -80..."
23,10/19/2021 14:22,Santa Barbara Channel Marine BON: Nearshore ke...,This dataset contains counts of epibenthic alg...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '32.8 -120.634483...",GeoShape,32.8 -120.6344833 34.87315 -118.4,NaN,NaN,NaN,"POLYGON((-120.6344833 34.87315, -118.4 34.8731...","POLYGON ((-120.63448 34.87315, -118.4 34.87315..."
24,10/19/2021 14:22,Southern California Bight Marine BON: Integrat...,This dataset contains cover of kelp forest ses...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '32.8 -120.65022 ...",GeoShape,32.8 -120.65022 34.87315 -118.4,NaN,NaN,NaN,"POLYGON((-120.65022 34.87315, -118.4 34.87315,...","POLYGON ((-120.65022 34.87315, -118.4 34.87315..."
25,10/19/2021 14:22,Southern California Bight Marine BON: cummulat...,Dataset contains all species from datasets of ...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '32.8 -120.65022 ...",GeoShape,32.8 -120.65022 34.87315 -118.4,NaN,NaN,NaN,"POLYGON((-120.65022 34.87315, -118.4 34.87315,...","POLYGON ((-120.65022 34.87315, -118.4 34.87315..."
26,10/19/2021 14:22,SBC LTER: Time series of quarterly NetCDF file...,This data is a time series of canopy area of g...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '27.01 -124.77 48...",GeoShape,27.01 -124.77 48.40 -114.04,NaN,NaN,NaN,"POLYGON((-124.77 48.4, -114.04 48.4, -114.04 2...","POLYGON ((-124.77 48.4, -114.04 48.4, -114.04 ..."
27,10/19/2021 14:22,Santa Barbara Channel Coastal and Island fish ...,citizen scientist monitoring data for rocky re...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '34.4030 -120.066...",GeoShape,34.4030 -120.0669 34.4611 -119.8660,NaN,NaN,NaN,"POLYGON((-120.0669 34.4611, -119.866 34.4611, ...","POLYGON ((-120.0669 34.4611, -119.866 34.4611,..."
29,10/19/2021 14:22,Santa Barbara Channel fish surveys at deep ree...,fish surveys from deep natural reefs in the no...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '33.91 -119.52 34...",GeoShape,33.91 -119.52 34.01 -119.45,NaN,NaN,NaN,"POLYGON((-119.52 34.01, -119.45 34.01, -119.45...","POLYGON ((-119.52 34.01, -119.45 34.01, -119.4..."
31,10/19/2021 14:22,NWFSC fish and invertebrate diversity derived ...,This dataset presents the community structure ...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '31.9 -121.15 34....",GeoShape,31.9 -121.15 34.5 -117.27,NaN,NaN,NaN,"POLYGON((-121.15 34.5, -117.27 34.5, -117.27 3...","POLYGON ((-121.15 34.5, -117.27 34.5, -117.27 ..."
32,10/19/2021 14:22,Plumes and Blooms: Curated oceanographic and p...,"The Plumes and Blooms project (PnB), has condu...",,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '33.3 -79.21 33.3...",GeoShape,33.3 -79.21 33.38 -79.17,NaN,NaN,NaN,"POLYGON((-79.21 33.38, -79.17 33.38, -79.17 33...","POLYGON ((-79.21 33.38, -79.17 33.38, -79.17 3..."
33,10/19/2021 14:22,SBC LTER: Beach: Time-series of beach wrack co...,"composition, count, and wet biomass of macroin...",,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '40.23 -96.34 43....",GeoShape,40.23 -96.34 43.25 -90.12,NaN,NaN,NaN,"POLYGON((-96.34 43.25, -90.12 43.25, -90.12 40...","POLYGON ((-96.34 43.25, -90.12 43.25, -90.12 4..."
34,10/19/2021 14:22,SBC LTER: Beach: Time series of abundance of b...,"distribution, abundance and seasonal occurrenc...",,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '33.1855666666666...",GeoShape,33.185566666666666 -81.75708055555556 33.37228...,NaN,NaN,NaN,POLYGON((-81.75708055555556 33.372280555555555...,"POLYGON ((-81.75708 33.37228, -81.50801 33.372..."
36,10/19/2021 14:22,Santa Barbara Channel fish and invertebrate su...,Counts of fish and invertebrates at nine oil a...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '33.56 -120.73 34...",GeoShape,33.56 -120.73 34.61 -118.11,NaN,NaN,NaN,"POLYGON((-120.73 34.61, -118.11 34.61, -118.11...","POLYGON ((-120.73 34.61, -118.11 34.61, -118.1..."
37,10/19/2021 14:22,Santa Barbara Channel fish surveys at shallow ...,"Fish surveys at nine nearshore, shallow-water ...",,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '34.48 -120.487 3...",GeoShape,34.48 -120.487 34.013 -119.379,NaN,NaN,NaN,"POLYGON((-120.487 34.013, -119.379 34.013, -11...","POLYGON ((-120.487 34.013, -119.379 34.013, -1..."
38,10/19/2021 14:22,Santa Barbara Channel fish surveys at shallow ...,fish counts surveyed in the shallow sections (...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '33.56 -120.73 34...",GeoShape,33.56 -120.73 34.61 -118.11,NaN,NaN,NaN,"POLYGON((-120.73 34.61, -118.11 34.61, -118.11...","POLYGON ((-120.73 34.61, -118.11 34.61, -118.1..."
51,8/9/2021 16:46:29,Time series of zooplankton abundance of the So...,Sampling is carried out bi-monthly on the R/V ...,,Enrique Montes (College of Marine Science of t...,emontesh@usf.edu,Tylar Murray (College of Marine Science of the...,tylarmurray@usf.edu,SE US,GCOOS,...,,5/3/2022: put this on hold because all we can ...,"{'@type': 'GeoShape', 'polygon': '-81.717 24.4...",GeoShape,NaN,NaN,NaN,"-81.717 24.478,-81.717 25.35167,-80.38 25.3516...","POLYGON ((-81.717 24.478,-81.717 25.35167,-80....","POLYGON ((-81.717 24.478, -81.717 25.35167, -8..."
55,8/4/2021 20:06:46,"Nearshore kelp forest integrated fish, 1981-on...",This dataset contains counts of fish (includin...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '32.8 -120.634483...",GeoShape,32.8 -120.6344833 34.87315 -118.4,NaN,NaN,NaN,"POLYGON((-120.6344833 34.87315, -118.4 34.8731...","POLYGON ((-120.63448 34.87315, -118.4 34.87315..."

In [13]:
df.loc[~df['@type'].isna()]

,Timestamp,Dataset title,Dataset summary,Crossfunded? (Yes/No),Who is the data management POC for the dataset?,Data management POC email:,Who is the technical POC for the dataset?,Technical POC email:,Which MBON project is this dataset associated with?,"If you have worked with a Regional Association, please indicate which one(s).",...,What is the expected timeline for this dataset?,additonal comments,spatialCoverage,@type,box,latitude,longitude,polygon,wkt,geometry
2,9/10/2024 15:27:50,South Florida Fisheries Habitat Assessment (FW...,taxa occurrence. Six seagrass species; ~36k re...,,Luke McEachron,Lucas.McEachron@myfwc.com,Luke McEachron,Lucas.McEachron@myfwc.com,SE US,,...,,,"{'@type': 'GeoShape', 'box': '24.647 26.785 -8...",GeoShape,24.647 26.785 -82.705 -79.277,NaN,NaN,NaN,"POLYGON((26.785 -82.705, -79.277 -82.705, -79....","POLYGON ((26.785 -82.705, -79.277 -82.705, -79..."
21,6/20/2023 13:47:54,Time series of zooplankton abundance in South ...,Sampling are carried out bi-monthly on the R/V...,,"Digna Rueda-Roa (College of Marine Science, Un...",druedaro@usf.edu,Tylar Murray / Sebastian DiGeronimo (College ...,tylarmurray@usf.edu / sebastian15@usf.edu,SE US,GCOOS,...,"Please, put this in hold. \nWe uploaded a part...",,"{'@type': 'GeoShape', 'box': '24.476 25.006 -8...",GeoShape,24.476 25.006 -81.715 -80.379,NaN,NaN,NaN,"POLYGON((25.006 -81.715, -80.379 -81.715, -80....","POLYGON ((25.006 -81.715, -80.379 -81.715, -80..."
23,10/19/2021 14:22,Santa Barbara Channel Marine BON: Nearshore ke...,This dataset contains counts of epibenthic alg...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '32.8 -120.634483...",GeoShape,32.8 -120.6344833 34.87315 -118.4,NaN,NaN,NaN,"POLYGON((-120.6344833 34.87315, -118.4 34.8731...","POLYGON ((-120.63448 34.87315, -118.4 34.87315..."
24,10/19/2021 14:22,Southern California Bight Marine BON: Integrat...,This dataset contains cover of kelp forest ses...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '32.8 -120.65022 ...",GeoShape,32.8 -120.65022 34.87315 -118.4,NaN,NaN,NaN,"POLYGON((-120.65022 34.87315, -118.4 34.87315,...","POLYGON ((-120.65022 34.87315, -118.4 34.87315..."
25,10/19/2021 14:22,Southern California Bight Marine BON: cummulat...,Dataset contains all species from datasets of ...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '32.8 -120.65022 ...",GeoShape,32.8 -120.65022 34.87315 -118.4,NaN,NaN,NaN,"POLYGON((-120.65022 34.87315, -118.4 34.87315,...","POLYGON ((-120.65022 34.87315, -118.4 34.87315..."
26,10/19/2021 14:22,SBC LTER: Time series of quarterly NetCDF file...,This data is a time series of canopy area of g...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '27.01 -124.77 48...",GeoShape,27.01 -124.77 48.40 -114.04,NaN,NaN,NaN,"POLYGON((-124.77 48.4, -114.04 48.4, -114.04 2...","POLYGON ((-124.77 48.4, -114.04 48.4, -114.04 ..."
27,10/19/2021 14:22,Santa Barbara Channel Coastal and Island fish ...,citizen scientist monitoring data for rocky re...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '34.4030 -120.066...",GeoShape,34.4030 -120.0669 34.4611 -119.8660,NaN,NaN,NaN,"POLYGON((-120.0669 34.4611, -119.866 34.4611, ...","POLYGON ((-120.0669 34.4611, -119.866 34.4611,..."
29,10/19/2021 14:22,Santa Barbara Channel fish surveys at deep ree...,fish surveys from deep natural reefs in the no...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '33.91 -119.52 34...",GeoShape,33.91 -119.52 34.01 -119.45,NaN,NaN,NaN,"POLYGON((-119.52 34.01, -119.45 34.01, -119.45...","POLYGON ((-119.52 34.01, -119.45 34.01, -119.4..."
31,10/19/2021 14:22,NWFSC fish and invertebrate diversity derived ...,This dataset presents the community structure ...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '31.9 -121.15 34....",GeoShape,31.9 -121.15 34.5 -117.27,NaN,NaN,NaN,"POLYGON((-121.15 34.5, -117.27 34.5, -117.27 3...","POLYGON ((-121.15 34.5, -117.27 34.5, -117.27 ..."
32,10/19/2021 14:22,Plumes and Blooms: Curated oceanographic and p...,"The Plumes and Blooms project (PnB), has condu...",,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '33.3 -79.21 33.3...",GeoShape,33.3 -79.21 33.38 -79.17,NaN,NaN,NaN,"POLYGON((-79.21 33.38, -79.17 33.38, -79.17 33...","POLYGON ((-79.21 33.38, -79.17 33.38, -79.17 3..."
33,10/19/2021 14:22,SBC LTER: Beach: Time-series of beach wrack co...,"composition, count, and wet biomass of macroin...",,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '40.23 -96.34 43....",GeoShape,40.23 -96.34 43.25 -90.12,NaN,NaN,NaN,"POLYGON((-96.34 43.25, -90.12 43.25, -90.12 40...","POLYGON ((-96.34 43.25, -90.12 43.25, -90.12 4..."
34,10/19/2021 14:22,SBC LTER: Beach: Time series of abundance of b...,"distribution, abundance and seasonal occurrenc...",,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '33.1855666666666...",GeoShape,33.185566666666666 -81.75708055555556 33.37228...,NaN,NaN,NaN,POLYGON((-81.75708055555556 33.372280555555555...,"POLYGON ((-81.75708 33.37228, -81.50801 33.372..."
36,10/19/2021 14:22,Santa Barbara Channel fish and invertebrate su...,Counts of fish and invertebrates at nine oil a...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '33.56 -120.73 34...",GeoShape,33.56 -120.73 34.61 -118.11,NaN,NaN,NaN,"POLYGON((-120.73 34.61, -118.11 34.61, -118.11...","POLYGON ((-120.73 34.61, -118.11 34.61, -118.1..."
37,10/19/2021 14:22,Santa Barbara Channel fish surveys at shallow ...,"Fish surveys at nine nearshore, shallow-water ...",,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '34.48 -120.487 3...",GeoShape,34.48 -120.487 34.013 -119.379,NaN,NaN,NaN,"POLYGON((-120.487 34.013, -119.379 34.013, -11...","POLYGON ((-120.487 34.013, -119.379 34.013, -1..."
38,10/19/2021 14:22,Santa Barbara Channel fish surveys at shallow ...,fish counts surveyed in the shallow sections (...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '33.56 -120.73 34...",GeoShape,33.56 -120.73 34.61 -118.11,NaN,NaN,NaN,"POLYGON((-120.73 34.61, -118.11 34.61, -118.11...","POLYGON ((-120.73 34.61, -118.11 34.61, -118.1..."
39,10/19/2021 14:22,Data to support manuscript: A Comparison of Tw...,fish dataset was collected at platform Harmony...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoCoordinates', 'latitude': '34.37...",GeoCoordinates,NaN,34.37,-120.16,NaN,NaN,POINT (-120.16 34.37)
41,10/19/2021 14:22,Santa Barbara Channel Marine BON: Gray Whales ...,dataset documents the passage of gray whales (...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoCoordinates', 'latitude': '34.40...",GeoCoordinates,NaN,34.40766,-119.877969,NaN,NaN,POINT (-119.87797 34.40766)
51,8/9/2021 16:46:29,Time series of zooplankton abundance of the So...,Sampling is carried out bi-monthly on the R/V ...,,Enrique Montes (College of Marine Science of t...,emontesh@usf.edu,Tylar Murray (College of Marine Science of the...,tylarmurray@usf.edu,SE US,GCOOS,...,,5/3/2022: put this on hold because all we can ...,"{'@type': 'GeoShape', 'polygon': '-81.717 24.4...",GeoShape,NaN,NaN,NaN,"-81.717 24.478,-81.717 25.35167,-80.38 25.3516...","POLYGON ((-81.717 24.478,-81.717 25.35167,-80....","POLYGON ((-81.717 24.478, -81.717 25.35167, -8..."
55,8/4/2021 20:06:46,"Nearshore kelp forest integrated fish, 1981-on...",This dataset contains counts of fish (includin...,,"Information Manager, Southern California Bight...",sbcbon@msi.ucsb.edu,Li Kui,sbcbon@msi.ucsb.edu,Southern California Bight,SCCOOS,...,,,"{'@type': 'GeoShape', 'box': '32.8 -120.634483...",GeoShape,32.8 -120.6344833 34.87315 -118.4,NaN,NaN,NaN,"POLYGON((-120.6344833 34.87315, -118.4 34.8731...","POLYGON ((-120.63448 34.87315, -118.4 34.87315..."

In [14]:
!pip install folium matplotlib mapclassify

Requirement already satisfied: folium in /usr/local/lib/python3.11/dist-packages (0.19.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (3.10.0)
Requirement already satisfied: mapclassify in /usr/local/lib/python3.11/dist-packages (2.8.1)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from folium) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.11/dist-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from folium) (1.26.4)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.11/dist-packages (from folium) (2025.1.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (2.8.2)
Requirement already satisfied: networkx>=2.7 in /usr/local/lib/python3.11/dist-packages (from mapclassify) (3.4.2)
Requirement already satisfied: pandas!=1.5.0,>=1.4 in /usr/local/lib/python3.11/dist-packages (from mapclassify) (2.2.2)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.11/dist-packages (from mapclassify) (1.6.1)
Requirement already satisfied: scipy>=1.8 in /usr/local/lib/python3.11/dist-packages (from mapclassify) (1.14.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2>=2.9->folium) (3.0.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.5.0,>=1.4->mapclassify) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.5.0,>=1.4->mapclassify) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.0->mapclassify) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.0->mapclassify) (3.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->folium) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->folium) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->folium) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->folium) (2025.1.31)

In [25]:
gdf = gpd.GeoDataFrame(df, geometry=df['geometry'], crs = 'epsg:4326')

gdf

,Timestamp,Dataset title,Dataset summary,Crossfunded? (Yes/No),Who is the data management POC for the dataset?,Data management POC email:,Who is the technical POC for the dataset?,Technical POC email:,Which MBON project is this dataset associated with?,"If you have worked with a Regional Association, please indicate which one(s).",...,What is the expected timeline for this dataset?,additonal comments,spatialCoverage,@type,box,latitude,longitude,polygon,wkt,geometry
0,9/10/2024 15:30:54,Marine Invertebrate Voucher Specimens (FWC-Col...,taxa occurrence. 1950-present,,Luke McEachron,Lucas.McEachron@myfwc.com,Luke McEachron,Lucas.McEachron@myfwc.com,SE US,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1,9/10/2024 15:29:13,SEMAP-South Atlantic trawl surveys,1983-Present. conversion to DarwinCore in prog...,,"Jennifer Dorton, Kyle Wilcox","jdorton@secoora.org, Kyle@axiomdatascience.com","Jennifer Dorton, Kyle Wilcox","jdorton@secoora.org, Kyle@axiomdatascience.com",SE US,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2,9/10/2024 15:27:50,South Florida Fisheries Habitat Assessment (FW...,taxa occurrence. Six seagrass species; ~36k re...,,Luke McEachron,Lucas.McEachron@myfwc.com,Luke McEachron,Lucas.McEachron@myfwc.com,SE US,,...,,,"{'@type': 'GeoShape', 'box': '24.647 26.785 -8...",GeoShape,24.647 26.785 -82.705 -79.277,NaN,NaN,NaN,"POLYGON((26.785 -82.705, -79.277 -82.705, -79....","POLYGON ((26.785 -82.705, -79.277 -82.705, -79..."
3,9/10/2024 15:25:10,FKNMS WS Pigment Phytoplankton,generation of taxa output in progress.,,Sebastian,sebastian15@usf.edu,Sebastian,sebastian15@usf.edu,SE US,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
4,9/10/2024 15:23:24,Walton Smith Primary Productivity,On Ian Smith's desktop,,Ian Smith,Ian.Smith@noaa.gov,Ian Smith,Ian.Smith@noaa.gov,SE US,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,,"Marine Bird Sighting Data, Arctic Marine Biodi...",,,,,Adrienne Canino @ Axiom,,Arctic,AOOS,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
60,,Vessel line-transect surveys of Arctic cetacea...,,,,,Adrienne Canino @ Axiom,,Arctic,AOOS,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
61,,Vessel line-transect surveys of Arctic pinnipe...,,,,,Adrienne Canino @ Axiom,,Arctic,AOOS,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
62,,Vessel line-transect surveys of Arctic marine ...,,,,,Adrienne Canino @ Axiom,,Arctic,AOOS,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
63,,"Abundance of Rocky Reef Fishes, Invertebrates ...",,,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

In [26]:
gdf.columns.tolist()

['Timestamp',
 'Dataset title',
 'Dataset summary',
 'Crossfunded? (Yes/No)',
 'Who is the data management POC for the dataset? ',
 'Data management POC email:',
 'Who is the technical POC for the dataset? ',
 'Technical POC email:',
 'Which MBON project is this dataset associated with?',
 'If you have worked with a Regional Association, please indicate which one(s).',
 'Are there any deadlines associated with this dataset?',
 'If one exists, enter the DOI for the dataset.',
 'If one exists, enter a citation for the dataset.',
 'Are the data accessible via the web?',
 'If yes to above, please include appropriate link(s) here.',
 'Has the dataset been loaded into ERDDAP?',
 'If yes to above, please include appropriate ERDDAP link(s) here.',
 'Has the dataset been translated into DarwinCore?',
 'Has the dataset been submitted to OBIS?',
 'If yes to above, please include appropriate OBIS link(s) here.',
 'Has the dataset been archived at NCEI?',
 'If yes to above, please include appropriate NCEI link(s) here.',
 'What is the current format of the data?',
 'What is the current format of the metadata?',
 'How frequently will the data be updated?',
 'Are there any relationships this dataset has with other observations?',
 'Are there any specific visualizations requested for the dataset?',
 'Is the dataset affiliated with other programs? For example, BOEM.',
 'Upload the dataset.',
 'Are there scripts or code used to process the data?',
 'If yes to above, and they are publicly available, please include appropriate link(s) here.',
 'If yes to above, and the code is available, please include appropriate link(s) here.',
 'Would you like this dataset visualized in the MBON Data Portal (https://mbon.ioos.us/)?',
 'Email Address',
 'If the dataset is already visualized in the MBON data portal, please include the link(s) to the data layer(s) here.',
 '',
 'What is the expected timeline for this dataset?',
 'additonal comments',
 'spatialCoverage',
 '@type',
 'box',
 'latitude',
 'longitude',
 'polygon',
 'wkt',
 'geometry']

In [27]:
gdf[(gdf['Dataset title']!= 'South Florida Fisheries Habitat Assessment (FWC-Seagrass)') & (gdf['Dataset title']!= 'Time series of zooplankton abundance in South Florida from 2015 onward (MBON program)')].explore(tooltip=['Dataset title','spatialCoverage'], popup=['Dataset title','spatialCoverage','wkt','If yes to above, please include appropriate link(s) here.'])

In [18]:
gdf.loc[gdf['Dataset title'] == 'South Florida Fisheries Habitat Assessment (FWC-Seagrass)',['box','wkt','If yes to above, please include appropriate link(s) here.']]

,box,wkt,"If yes to above, please include appropriate link(s) here."
2,24.647 26.785 -82.705 -79.277,"POLYGON((26.785 -82.705, -79.277 -82.705, -79....",10.15468/h585qq

In [19]:
gdf.loc[gdf['Dataset title'] == 'Time series of zooplankton abundance in South Florida from 2015 onward (MBON program)', ['box','wkt','If yes to above, please include appropriate link(s) here.']]

,box,wkt,"If yes to above, please include appropriate link(s) here."
21,24.476 25.006 -81.715 -80.379,"POLYGON((25.006 -81.715, -80.379 -81.715, -80....",10.15468/buqg4u

In [20]:
gdf.loc[gdf['Dataset title'] == 'SBC LTER: Time series of quarterly NetCDF files of kelp biomass in the canopy from Landsat 5, 7 and 8, since 1984 (ongoing)', ['box','wkt','If yes to above, please include appropriate link(s) here.']]

,box,wkt,"If yes to above, please include appropriate link(s) here."
26,27.01 -124.77 48.40 -114.04,"POLYGON((-124.77 48.4, -114.04 48.4, -114.04 2...",https://portal.edirepository.org/nis/mapbrowse...

In [21]:
df['If yes to above, please include appropriate link(s) here.'].unique()

array(['10.15468/bfd6ci', '', '10.15468/h585qq',
       'https://safmc.net/wp-content/uploads/2022/05/SG_A1a_EwE-Report_Dec2021.pdf',
       'https://usf.box.com/s/dvoi1ve0jn3apbdlad114uhn0pvmjool',
       'https://grunt.sefsc.noaa.gov/rvc_analysis20/samples/index',
       'https://ecotaxa.obs-vlfr.fr/prj/9989',
       'https://data.piscoweb.org/metacatui/view/doi%3A10.6085%2FAA%2Fmarine_cbs.5.6',
       'https://pubmed.ncbi.nlm.nih.gov/29937700/', '10.15468/buqg4u ',
       'http://www.neracoos.org/erddap/info/WBTS_CFIN_2004_2017/index.html',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=5',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=3',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=7',
       'https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=74',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=141',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=484',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=110',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=485',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=486',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=134',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=91',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=51',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=646',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=111',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=112',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=113',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=470',
       'https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=61',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=257',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=109',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier1145',
       'https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=702',
       'https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-cce&identifier=255',
       'https://data.piscoweb.org/metacatui/view/doi%3A10.6085%2FAA%2Fmarine_ltm.12.5',
       'https://www.glerl.noaa.gov/glansis/mapExplorer.php',
       'https://www.glerl.noaa.gov/data/waterlife/',
       'https://cwcgom.aoml.noaa.gov/thredds/dodsC/SEASCAPE_8DAY/SEASCAPES.nc',
       'https://obis.org/dataset/afef5da2-614b-4208-aee6-c2413ed5ab76',
       'https://opc.dataone.org/view/doi%3A10.25494%2FP6901R',
       'https://opc.dataone.org/view/doi%3A10.25494%2FP6JS3M\nhttps://opc.dataone.org/view/doi%3A10.25494%2FP69885\nhttps://opc.dataone.org/view/doi%3A10.25494%2FP65K5W\nhttps://opc.dataone.org/view/doi%3A10.25494%2FP6F30N',
       'https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.nodc:0177837'],
      dtype=object)

In [22]:
# script =<script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
#         <script type="text/javascript" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
#         <script>
#         $(document).ready( function () {
#             $('#table').DataTable();
#         } );
#         let table = new DataTable('#table');
#         </script>